# Generated by Django 2.0.6 on 2018-06-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='img',
            field=models.ImageField(default=1, upload_to='Places'),
            preserve_default=False,
        ),
    ]
