# Generated by Django 2.0.6 on 2018-06-27 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20180627_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=4000)),
                ('img', models.ImageField(upload_to='Places')),
                ('Subimg1', models.ImageField(upload_to='Places')),
                ('Subimg2', models.ImageField(upload_to='Places')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantes', to='blog.Lugar')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
