# Generated by Django 2.0.6 on 2018-06-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180627_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='Subimg1',
            field=models.ImageField(blank=True, upload_to='Places'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='Subimg2',
            field=models.ImageField(blank=True, upload_to='Places'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='Subimg3',
            field=models.ImageField(blank=True, upload_to='Places'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='Subimg4',
            field=models.ImageField(blank=True, upload_to='Places'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='Subimg1',
            field=models.ImageField(blank=True, upload_to='Places'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='Subimg2',
            field=models.ImageField(blank=True, upload_to='Places'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='img',
            field=models.ImageField(blank=True, upload_to='Places'),
        ),
    ]
