# Generated by Django 2.0.6 on 2018-06-28 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_lugar_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
