# Generated by Django 2.0.6 on 2018-06-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180628_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='created_by',
        ),
    ]
